artifact_uri: file:///home/runner/work/introducao-ciclo-de-vida-de-modelos/introducao-ciclo-de-vida-de-modelos/aula_06_cicd_automacao/mlruns_ci/249755071298649575/612cd8cdd9884dafb8bc13478e43864e/artifacts
end_time: 1768508104408
entry_point_name: ''
experiment_id: '249755071298649575'
lifecycle_stage: active
run_id: 612cd8cdd9884dafb8bc13478e43864e
run_name: random_forest_training
source_name: ''
source_type: 4
source_version: ''
start_time: 1768508101687
status: 3
tags: []
user_id: runner
