artifact_uri: file:///home/runner/work/introducao-ciclo-de-vida-de-modelos/introducao-ciclo-de-vida-de-modelos/aula_06_cicd_automacao/mlruns_ci/249755071298649575/23894b43ad5b4633ae58bd8310830b15/artifacts
end_time: 1768517591531
entry_point_name: ''
experiment_id: '249755071298649575'
lifecycle_stage: active
run_id: 23894b43ad5b4633ae58bd8310830b15
run_name: random_forest_training
source_name: ''
source_type: 4
source_version: ''
start_time: 1768517588867
status: 3
tags: []
user_id: runner
