artifact_location: file:///home/runner/work/introducao-ciclo-de-vida-de-modelos/introducao-ciclo-de-vida-de-modelos/aula_06_cicd_automacao/mlruns_ci/249755071298649575/models/m-96dc9fcc1f5540d4be6cf8dc6e6e4e5d/artifacts
creation_timestamp: 1763865109947
experiment_id: '249755071298649575'
last_updated_timestamp: 1763865112447
lifecycle_stage: deleted
model_id: m-96dc9fcc1f5540d4be6cf8dc6e6e4e5d
model_type: null
name: model
source_run_id: eae5350c85fd4f44aa8014853a15c4ff
status: 2
status_message: null
